[package]
categories = ["parsing", "text-editors"]
description = "lean grammar for the tree-sitter parsing library"
edition = "2018"
keywords = ["incremental", "parsing", "lean"]
name = "tree-sitter-lean"
repository = "https://github.com/wvhulle/tree-sitter-lean"
version = "0.0.1"

build = "build.rs"
include = ["build.rs", "src/*", "grammar.js", "grammar/*"]

[dependencies]
tree-sitter = "0.25"

[build-dependencies]
cc = "1.0"
